apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    version: {{ .Chart.AppVersion }}
    heritage: {{ .Release.Service }}
spec:
{{- if .Values.kibana.enabled }}
  kibana:
    image: {{ .Values.kibana.image }}
{{- end }}
{{- if .Values.cerebro.enabled }}
  cerebro:
    image: {{ .Values.cerebro.image }}
{{- end }}
  elastic-search-image: {{ .Values.elasticsearch.image }}
  client-node-replicas: {{ .Values.elasticsearch.clientReplicas }}
  master-node-replicas: {{ .Values.elasticsearch.masterReplicas }}
  data-node-replicas: {{ .Values.elasticsearch.dataReplicas }}
  network-host: 0.0.0.0
{{- if .Values.elasticsearch.zones }}
  zones:
{{ toYaml .Values.elasticsearch.zones | indent 4 }}
{{- else }}
  zones: []
{{- end }}
  data-volume-size: {{ .Values.elasticsearch.storage.volumeSize }}
  java-options: {{ .Values.elasticsearch.javaOpts | quote }}
{{- if .Values.elasticsearch.snapshot.enabled }}
  snapshot:
    scheduler-enabled: {{ .Values.elasticsearch.snapshot.enabled }}
    bucket-name: {{ .Values.elasticsearch.snapshot.bucketName }}
    cron-schedule: {{ .Values.elasticsearch.snapshot.schedule | quote }}
{{-   if .Values.elasticsearch.snapshot.authentication.enabled }}
    authentication:
     password: {{ .Values.elasticsearch.snapshot.authentication.password }}
     username: {{ .Values.elasticsearch.snapshot.authentication.username }}
{{-   end }}
{{- end }}
  storage:
{{- if .Values.elasticsearch.storage.storageClass }}
    storage-class: {{ .Values.elasticsearch.storage.storageClass | quote }}
{{- else }}
    type: {{ .Values.elasticsearch.storage.type }}
    storage-class-version: {{ .Values.elasticsearch.storage.classVersion }}
{{- end }}
    volume-reclaim-policy: {{ .Values.elasticsearch.storage.reclaimPolicy }}
{{- if .Values.statsd.enabled }}
  statsd-host: {{ .Values.statsd.host }}
{{- end }}
  resources:
{{ .Values.elasticsearch.resources | toYaml | indent 4 }}
