apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-fluentd
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
        app: {{ template "name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        version: {{ .Chart.AppVersion }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: fluentd
          image: quay.io/fluent/fluentd-kubernetes-daemonset
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch-{{ .Release.Name }}"
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: "9200"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibcontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibcontainers
          hostPath:
            path: /var/lib/docker/containers
